<a href="https://colab.research.google.com/github/won462/2026bda/blob/main/06w_dataframe_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

pf= pd.DataFrame(data = [[25, 35, 8,18],
                  [18,27,10,20],
                  [17,17,10,19],
                  [12,22,9,20],
                  [22,34,8,16]],
                  index =['윤일형','강수희','홍소희','유한빈','신수빈'],
                  columns=['중간','기말','과제','출석']
)

In [ ]:
pf.과제

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [ ]:
pf[['과제']]

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

In [ ]:
import numpy as np
import pandas as pd

s= pd.Series([1,3,5, np.nan,6,8],name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [ ]:
s.name

'first'

In [ ]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [ ]:
s.shape

(6,)

In [ ]:
s.size

6

In [ ]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [ ]:
s[1]

np.float64(3.0)

In [ ]:
s[1:5]

1    3.0
2    5.0
3    NaN
4    6.0
Name: first, dtype: float64

In [ ]:
s.index = list('abcdef')
s

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [ ]:
print(s['b'],s['d'])

3.0 nan

In [ ]:
s['c':'e']

c    5.0
d    NaN
e    6.0
Name: first, dtype: float64

In [ ]:
s['b':'f']

b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [ ]:
s[0:3]

a    1.0
b    3.0
c    5.0
Name: first, dtype: float64

In [ ]:
s1 = s[1:4]
s1

b    3.0
c    5.0
d    NaN
Name: first, dtype: float64

In [ ]:
s1[0]

/tmp/ipykernel_5663/643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.float64(3.0)

In [ ]:
s1[0]=10
s1

/tmp/ipykernel_5663/2709485624.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s1[0]=10

b    10.0
c     5.0
d     NaN
Name: first, dtype: float64

In [ ]:
s

a     1.0
b    10.0
c     5.0
d     NaN
e     6.0
f     8.0
Name: first, dtype: float64

In [ ]:
s.index = np.arange(1,7)
s

1     1.0
2    10.0
3     5.0
4     NaN
5     6.0
6     8.0
Name: first, dtype: float64

In [ ]:
s[1]

np.float64(1.0)

In [ ]:
s[0]

KeyError: 0

In [ ]:
s[1:3]

2    10.0
3     5.0
Name: first, dtype: float64

In [ ]:
import pandas as pd

age =pd.Series([9,17,32,45,65,98], index=list('abcdef'),name='age')
age

a     9
b    17
c    32
d    45
e    65
f    98
Name: age, dtype: int64

In [ ]:
age['b']

np.int64(17)

In [ ]:
age[[1,3,5]]

/tmp/ipykernel_5663/2675513065.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  age[[1,3,5]]

b    17
d    45
f    98
Name: age, dtype: int64

In [ ]:
age[['a','f','d']]

a     9
f    98
d    45
Name: age, dtype: int64

In [ ]:
age[['c']]

c    32
Name: age, dtype: int64

In [ ]:
import pandas as pd

s=pd.Series([3,6,-3,0,-4,8,-7])
s

0    3
1    6
2   -3
3    0
4   -4
5    8
6   -7
dtype: int64

In [ ]:
s>0

0     True
1     True
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [ ]:
s%2 ==0

0    False
1     True
2    False
3     True
4     True
5     True
6    False
dtype: bool

In [ ]:
s[s>0]

0    3
1    6
5    8
dtype: int64

In [ ]:
s[~(s > 0)]

2   -3
3    0
4   -4
6   -7
dtype: int64

In [ ]:
s[s%2 == 0]

1    6
3    0
4   -4
5    8
dtype: int64

In [ ]:
s[s%2 != 0]

0    3
2   -3
6   -7
dtype: int64

In [ ]:
s[(s>0)&(s%2 == 0)]

1    6
5    8
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
s=['희빈','수영','현수','지호','지민']
p =pd.Series([99,84,92,65,78], index=s)
p

희빈    99
수영    84
현수    92
지호    65
지민    78
dtype: int64

In [ ]:
p.name = '수학성적'
p.index.name = 'st_name'
p

st_name
희빈    99
수영    84
현수    92
지호    65
지민    78
Name: 수학성적, dtype: int64

In [ ]:
p.sort_values()

st_name
지호    65
지민    78
수영    84
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [ ]:
p.sort_values(ascending=False)

st_name
희빈    99
현수    92
수영    84
지민    78
지호    65
Name: 수학성적, dtype: int64

In [ ]:
p.sort_index()

st_name
수영    84
지민    78
지호    65
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [ ]:
p.sort_index(ascending=False)

st_name
희빈    99
현수    92
지호    65
지민    78
수영    84
Name: 수학성적, dtype: int64

In [ ]:
print(p.max())
print(p.min())

99
65

In [ ]:
print(p.count())
print(p.size)

5
5

In [ ]:
p.describe()

count     5.000000
mean     83.600000
std      13.088163
min      65.000000
25%      78.000000
50%      84.000000
75%      92.000000
max      99.000000
Name: 수학성적, dtype: float64

In [ ]:
import numpy as np
import pandas as pd

s=pd.Series([3,1,1,2,None,np.nan,4,6,6,np.nan])
s

0    3.0
1    1.0
2    1.0
3    2.0
4    NaN
5    NaN
6    4.0
7    6.0
8    6.0
9    NaN
dtype: float64

In [ ]:
s.values

array([ 3.,  1.,  1.,  2., nan, nan,  4.,  6.,  6., nan])

In [ ]:
s.count()

np.int64(7)

In [ ]:
s.value_counts()

1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [ ]:
s.value_counts(dropna=False)

NaN    3
1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [ ]:
s.value_counts(sort=False,dropna=False)

3.0    1
1.0    2
2.0    1
NaN    3
4.0    1
6.0    2
Name: count, dtype: int64

In [ ]:
s.value_counts(bins=4)

(0.994, 2.25]    3
(4.75, 6.0]      2
(2.25, 3.5]      1
(3.5, 4.75]      1
Name: count, dtype: int64

In [ ]:
s.value_counts(bins=4,sort=False)

(0.994, 2.25]    3
(2.25, 3.5]      1
(3.5, 4.75]      1
(4.75, 6.0]      2
Name: count, dtype: int64

In [ ]:
s.value_counts(bins=[0.5,3.5,6.5],sort=False)

(0.499, 3.5]    4
(3.5, 6.5]      3
Name: count, dtype: int64

In [ ]:
import pandas as pd
df = pd.DataFrame([10,20,30,40,50])
df

    0
0  10
1  20
2  30
3  40
4  50

In [ ]:
import pandas as pd

df = pd.DataFrame([[1,2,3],[10,20,30],[100,200,300]],index=list('abc'))
df

     0    1    2
a    1    2    3
b   10   20   30
c  100  200  300

In [ ]:
df = pd.DataFrame([[1,2,3],[10,20,30],[100,200,300]],
                  index=list('abc'),columns=['A','B','C']
)
df

     A    B    C
a    1    2    3
b   10   20   30
c  100  200  300

In [ ]:
print(df.index)
print(df.columns)

Index(['a', 'b', 'c'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')

In [ ]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame(data = np.arange(12).reshape(3,4))
df1

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame(np.random.randint(1,46,(5,6)))
df1

    0   1   2   3   4   5
0  19  40  18  10  21  15
1  21  30  16  40  15  37
2  32  28  21  36  29  33
3  20  37  20  37  40  44
4   5  43  28   7  19  25

In [ ]:
df1 = pd.DataFrame(np.random.random((5,3)))
df1

          0         1         2
0  0.130543  0.463722  0.746044
1  0.387047  0.958571  0.637043
2  0.741939  0.033166  0.429234
3  0.956973  0.690336  0.016016
4  0.140838  0.383494  0.138780

In [ ]:
df = pd.DataFrame({'국어':[82,76,67],'수학':[99,87,78]},index=['김국진','신영희','이길순'])
df

     국어  수학
김국진  82  99
신영희  76  87
이길순  67  78

In [ ]:
df.index

Index(['김국진', '신영희', '이길순'], dtype='object')

In [ ]:
df.columns

Index(['국어', '수학'], dtype='object')

In [ ]:
import pandas as pd

df =pd.DataFrame({'numbers':[1,2,3],
                  'colors':['red','white','blue']})
df

   numbers colors
0        1    red
1        2  white
2        3   blue

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.columns

Index(['numbers', 'colors'], dtype='object')

In [ ]:
courses = pd.Series(["Spark","PySpark","Hadoop"],name='courses')
courses

0      Spark
1    PySpark
2     Hadoop
Name: courses, dtype: object

In [ ]:
fees = pd.Series([250000,300000,20000], name='fees')
fees

0    250000
1    300000
2     20000
Name: fees, dtype: int64

In [ ]:
df= pd.DataFrame({courses.name: courses, fees.name: fees})
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop   20000

In [ ]:
import pandas as pd

df=pd.read_csv('2016년졸음운전.csv',
               encoding='euc-kr',index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [ ]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [ ]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [ ]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [ ]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [ ]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [ ]:
dfmean(axis=1)

NameError: name 'dfmean' is not defined

In [ ]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [ ]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [ ]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [ ]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [ ]:
df.max(axis=None)

522

In [ ]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [ ]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [ ]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [ ]:
df.min(axis=None)

4

In [ ]:
df[['사망(명)','부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [ ]:
df.iloc[:,1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [ ]:
df2=df.copy()
df2['재해자수'] =df[['사망(명)','부상(명)']].sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   NaN
2016년2월     174      6    328   NaN
2016년3월     217      7    435   NaN
2016년4월     216      7    419   NaN
2016년5월     239     13    522   NaN
2016년6월     200     12    362   NaN
2016년7월     227      9    460   NaN
2016년8월     230      7    490   NaN
2016년9월     187     13    347   NaN
2016년10월    183     10    367   NaN
2016년11월    200      5    418   NaN
2016년12월    168      4    364   NaN

In [ ]:
df2>10

          사고(건)  사망(명)  부상(명)   재해지수
연월
2016년1월    True  False   True  False
2016년2월    True  False   True  False
2016년3월    True  False   True  False
2016년4월    True  False   True  False
2016년5월    True   True   True  False
2016년6월    True   True   True  False
2016년7월    True  False   True  False
2016년8월    True  False   True  False
2016년9월    True   True   True  False
2016년10월   True  False   True  False
2016년11월   True  False   True  False
2016년12월   True  False   True  False

In [ ]:
df2[df2>10]

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월     192    NaN    387   NaN
2016년2월     174    NaN    328   NaN
2016년3월     217    NaN    435   NaN
2016년4월     216    NaN    419   NaN
2016년5월     239   13.0    522   NaN
2016년6월     200   12.0    362   NaN
2016년7월     227    NaN    460   NaN
2016년8월     230    NaN    490   NaN
2016년9월     187   13.0    347   NaN
2016년10월    183    NaN    367   NaN
2016년11월    200    NaN    418   NaN
2016년12월    168    NaN    364   NaN

In [ ]:
df2[ [True]*6 + [False]*7 ]

ValueError: Item wrong length 13 instead of 12.

In [ ]:
df2['재해자수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월     False
2016년4월     False
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월     False
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 재해자수, dtype: bool

In [ ]:
df2[df2['재해자수']>400]

Empty DataFrame
Columns: [사고(건), 사망(명), 부상(명), 재해자수]
Index: []

In [ ]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [ ]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [ ]:
df['사망(명)'].isin([7,10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [ ]:
df[df['사망(명)'].isin([7,10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [ ]:
df[df['사망(명)'].isin([7,10])|(df['부상(명)']>350)]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df[df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [ ]:
df3 =df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df3[df3>10]=df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364